### ISSUE TITLE
Uncaught TypeError: Quiet.setProfilesPrefix is not a function

### ISSUE THREAD

**Issue by emansih** [quiet/quiet-js#10]
Hello it's me again.

I copied the code from example/text folder from the repo and I can't run the javascript at all. Whenever I fire up /sendtext.html or /receivetext.html , Chrome developer tools will give the following error.

Uncaught TypeError: Quiet.setProfilesPrefix is not a function
    at sendtext.js:2
    at sendtext.js:53
(anonymous) @ sendtext.js:2
(anonymous) @ sendtext.js:53

I do have a LAMP stack and nodejs installed, but I am unsure what is wrong. Thanks for any help.

**Comment by emansih** [comment]
From  what I understand from the docs, setProfilesPrefix is looking for quiet-profiles.json in the path, yes, I do have quiet-profiles.json in the path

**Comment by brian-armstrong** [comment]
@emansih I'm so sorry - I changed the API and broke the examples and didn't realize it :(

I'll fix them later tonight. For now, you can browse the gh-pages branch which does use the new API

Initializing: https://github.com/quiet/quiet-js/blob/gh-pages/javascripts/quiet-init.js
Receiving: https://github.com/quiet/quiet-js/blob/gh-pages/javascripts/receivetext.js
Sending: https://github.com/quiet/quiet-js/blob/gh-pages/javascripts/sendtext.js

**Comment by emansih** [comment]
thanks.

**Comment by brian-armstrong** [comment]
Just a heads up - the ultrasonic-experimental profile won't work in quiet.js just yet. The emscripten part needs to be recompiled to take the new changes from libquiet. I had been putting it off but since it might come in handy for you I'll see what's left to distribute new emscripten blobs :)

**Comment by emansih** [comment]
I suppose you saw my repo. Yes, i have tried the ultrasonic-experimental profile and it crashes on Chrome. I knew there was a bug somewhere since ultrasonic-experimental works inside the lab. thanks anyway

**Comment by brian-armstrong** [comment]
Hi @emansih,

Just to give you and update, I have been working on bringing the features in the experimental profile to quiet.js. I have managed to get them working from JS-JS, but the interop from JS-Android doesn't function just yet. I'm going to investigate why this is and hope to have these changes working and pushed within a week.

**Comment by emansih** [comment]
@brian-armstrong  hey thanks. no hurry

**Comment by brian-armstrong** [comment]
@emansih 

So, I'm finally back. I have good news and I have bad news.

The good news is that I've finally got the interop working, and i'm ready to push changes to the JS repo.

The bad news is that I discovered a bug in the Android library. The fix for this bug will cause future versions of the library to be incompatible with the current version. As a result, new versions you push out after that will not be able to communicate with prior versions.

I'm not sure how you'd like to proceed. If you do see this and get a chance, I'd like to know if it'd be feasible to have you push out the new version, or if that's a game breaker for you. I do understand that this is a frustrating issue.

In the meantime, I've pushed the new version to a separate branch in the Android lib. The branch is `msequence_ordering`. You should be able to use this version to interop with JS.

**Comment by emansih** [comment]
@brian-armstrong It shouldn't be a game breaker for me, don't worry about it.
