### ISSUE TITLE
best audio profile for short messages from the iphone speaker?

### ISSUE THREAD

**Issue by jonroig** [quiet/quiet-js#5]
Hey there... first, let me say that this is a really neat project. Great examples really help sell its utility, so I really appreciate that. Thanks for all your hard work!

Here's my issue - I'm having a fair amount of trouble transmitting simple messages from the iPhone to my  computer. It does work sometimes, but what's the best way to help that happen reliably?

**Comment by brian-armstrong** [comment]
Well, it's hard to guess precisely what might cause this. Just to be sure, you're running the text transmit/receive example with the audible profile? Which browser are you using to receive with?

In my experience with using iPhone -> desktop/laptop, I'd say I've had pretty good luck with both profiles. It helps to make sure that the iPhone's speakers are pointed directly at the microphone on your computer, if possible. Transmission via echo/reverb is possible but less reliable. I'd also generally recommend trying quieter volumes rather than louder ones. Are you trying this in a location with a lot of ambient noise?

**Comment by jonroig** [comment]
Hey man... thanks for the quick response. 

I'm sending with an iPhone, receiving on a MacBook Pro, audible profile...  and yeah, but really, this is a more of a generic question, since if I use quiet.js in my project, it'll apply to a wide range of different scenarios phone to computer-type scenarios.  In an ideal world, I'm looking for an easy way to send a short blast of data super reliably without too much concern for transmission time.

Basically, my goal is to use something like quiet.js to initiate a connection between a phone and a computer, then connect them up more permanently behind the scenes. Sure, I could use QR codes to bridge that gap -- and I might -- but there's something super cool about quiet.js, it'd be a lot more fun to transmit a guid via audio then by the screen. 

Maybe what you've built is overkill for what I need?  Is there some area of your lab page that I should explore a bit?

Regardless, it's been fun playing with this project... thanks for making it!

**Comment by brian-armstrong** [comment]
Just to be clear, are you testing with https://quiet.github.io/quiet-js/index.html or https://quiet.github.io/quiet-js/lab.html ? The lab is currently only intended for "self" tests where the receiver and transmitter are the same. The lab numbers each frame so that it can track error and transmission rates, and there's presently no way of synchronizing this information, so it isn't possible to use the lab across devices, although getting that functionality is on my TODO list for sure.

I think your intended use sounds like a good match. I imagined that quiet could be used as a sort of audible QR code specifically, and I think it should work well that way. I imagine you could have the phone periodically send frames containing the guid until the remote API endpoint you've written tells it that another device has received it, or something like that.

Thank you for the kind words. If you get your project working, please do let me know, it sounds interesting.

**Comment by jonroig** [comment]
Yup. That's exactly my plan - send out bursts until the receiver registers a "hit." At that point, I'll signal back to the original client using sockets that it's all good and the connection has been made. 

I'm testing with https://quiet.github.io/quiet-js/index.html
I did get it that working - it turned out to be something with my Chrome browser itself on the receiving end, so that's all good. 

I'll just go with the regular "audible" profile for now, see how it goes.

**Comment by brian-armstrong** [comment]
Glad to hear you got it. The configuration on the receiver side is a little tricky. If there's anything that I can change to make that easier, please let me know
