### ISSUE TITLE
The demo doesn´t work

### ISSUE THREAD

**Issue by carlosguedes** [quiet/quiet-js#9]
Hello Guys, sorry for creating this issue but I´m having problems with the demo.

I tryed with Safari on Iphone, Chrome and Edge on Windows 10 but it doesn´t work. Can you guys fix it?

Thank you very much.

**Comment by brian-armstrong** [comment]
Hi,

Sorry to hear you're having troubles with the demo. I just tried it in Chrome and was able to get it to transmit.

Just to confirm, are you using the demo at https://quiet.github.io/quiet-js/ ? Are you using the audible mode or ultrasonic mode? Can you hear any sounds played when you transmit with audible mode?

**Comment by nmstoker** [comment]
I'm guessing it might be not be a trivial change, but if the demo could output some debug info easily on the receiving end, it might help people work out details what happened.

I had very patchy results transmitting from my laptop (Arch Linux + Chrome) to my mobile (Android / Chrome) with parts of the message getting through occasionally when using the audible mode. It never worked at all with the ultrasonic.  I couldn't receive on the laptop due to a mic issue that side (ie nothing to do w/ quiet.js!)

There were some messages about dropped packets, but not much more I could use to work anything useful out.  I tinkered with the volume levels and found 50% (as advised) did seem the best; orientation of the phone (eg to ensure the mic was optimally placed) didn't seem to make much difference.

**Comment by brian-armstrong** [comment]
The debug info is definitely something I want to make available. It's already exposed in libquiet, it's just a matter of moving it further up. Though, I might still be hesitant to expose all of it in an actual demo.

Just for an example, you can see some of the diagnostic statistics in this tool https://quiet.github.io/quiet-profile-lab . It's somewhat tricky to actually use the information though, and the decoder can't really know or suggest specific changes that have to be made.

**Comment by brian-armstrong** [comment]
I'm going to close this issue for inactivity/lack of details. @carlosguedes please feel free to open a new issue if you have more info.

@nmstoker Receiving on mobile is in general rather tricky. This is, I suspect, due in part to the inefficiency of running on js/emscripten combined with the limited compute power of the device. There could also be other factors in play, and I do intend to look into it more fully at some point.

I've released an Android binding which should work substantially better on that platform. It's not as convenient as using JS but it runs native code which is at least an order of magnitude more performant. Also, it invokes OpenSL directly which helps bypass noise cancellation features.

It's possible that mobile Chrome has some config options for web audio that the desktop one doesn't or that I'm somehow otherwise failing there. I do want to take a closer look at it but my suspicion is that the receiver either isn't keeping up/staying real-time or that Chrome enables some noise-cancellation that can't be turned off and which destroys the signal.
